language: ruby
rvm:
  - 2.3.5

services:
  - docker

before_install:
  - gem update --system
  - gem --version
  - docker build --rm=false -t registry.heroku.com/ana-mastermind-game/web .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com;
    docker push registry.heroku.com/ana-mastermind-game/web;
    fi
