language: ruby
rvm:
  - 2.3.5

before_install:
  - gem update --system
  - gem --version

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com;
    docker push registry.heroku.com/ana-mastermind-game/web;
    fi
