language: ruby
rvm:
  - 2.3.5

services:
  - docker

before_install:
  - gem update --system
  - gem --version

jobs:
  include:
    - stage: unit tests
      script: "bundle exec rspec spec"
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t ana-mastermind-game .
      - docker images
      - docker tag ana-mastermind-game $DOCKER_USERNAME/ana-mastermind-game
      - docker push $DOCKER_USERNAME/ana-mastermind-game
      if: branch = master
    - stage: deploy to dev
      env:
        - HEROKU_APP=dev-ana-mastermind-game
      script: ./scripts/deploy_container_heroku.sh
      if: branch = master
    - stage: test dev
      script: 'curl http://dev-ana-mastermind-game.herokuapp.com/health'
      if: branch = master
    - stage: deploy to qa
      env:
        - HEROKU_APP=qa-ana-mastermind-game
      script: ./scripts/deploy_container_heroku.sh
      if: branch = master
    - stage: test qa
      script: 'curl http://qa-ana-mastermind-game.herokuapp.com/health'
      if: branch = master
    - stage: deploy to prod
      env:
        - HEROKU_APP=ana-mastermind-game
      script: ./scripts/deploy_container_heroku.sh
      if: branch = master
    - stage: test prod
      script: 'curl http://ana-mastermind-game.herokuapp.com/health'
      if: branch = master
